name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install modules
        run: yarn

      - name: Run linters
        run: yarn lint

      - name: Run tests
        run: yarn test:ci

      - name: Deploy app
        env:
          USER_NAME: pgalias
          USER_EMAIL: pawel@galias.me
        run: |
          git config --global user.name $USER_NAME
          git config --global user.email $USER_EMAIL
          git remote set-url origin https://$USER_NAME:${{ secrets.PASS }}@github.com/${{ github.repository }}.git
          yarn deploy
